name: Python release github docs

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material -U
        cd evliess.github.io
        pip install mkdocs-minify-plugin -U
        mkdocs gh-deploy --config-file ../mkdocs/mkdocs.yml --remote-branch master
